version: '3'
services:
    mysql-development:
      image: mysql
      container_name: un-mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: test1234
        MYSQL_DATABASE: ejemplo
        MYSQL_USER: ejemplo
        MYSQL_PASSWORD: test1234
      working_dir: /var/lib/mysql
      volumes:
        - "../mysql-volume:/var/lib/mysql"
      restart: unless-stopped
    back-container:
      image: back-image
      container_name: back
      ports:
        - "3000:8080"
      depends_on:
        - mysql-development
