version: '3.8'
services:
    mariadb-container:
      image: mariadb:11.1.2
      environment:
        MARIADB_ROOT_PASSWORD: test1234
        MARIADB_DATABASE: socios
      ports:
        - 3306:3306
      restart: unless-stopped
    springboot-container:
      build: .
      ports:
        - 8080:80
      environment:
        - DB_URL=jdbc:mariadb://mariadb-container:3306/socios
        - DB_USER=root
        - PASSWORD=test1234
        - DDL_MODE=create-drop
        - SHOW_SQL=true
        - SQL_INIT=always
      restart: on-failure
