name: Docker Image BE
run-name: Creando la imagen del back end
on:
  push:
    branches:  
     - "dev" 

jobs:
 crear-imagen:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout de la branch
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # get all tags, needed to get git log
        ref: main
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag back-image:$(date +%s)
    - run: docker push ghcr.io/disilab-frba-utn-edu-ar/back-image:$(date +%s)

    - uses: ncipollo/release-action@v1
      with:
        name: ${{ env.GITHUB_REF_NAME }}
        tag: ${{ env.GITHUB_REF_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
