name: Dokku-Commands
on:
  workflow_dispatch:
  workflow_call:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HOST: ${{ secrets.SSH_HOST }}
  USER: ${{ secrets.SSH_USER }}
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  TOKEN_GHCR: ${{ secrets.TOKEN_GHCR }}

  
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

    - name: Cloning repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to ghcr.io
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER }}
        key: ${{ env.PRIVATE_KEY }}
        script:  registry:login ghcr.io pepinony ${{ env.TOKEN_GHCR }}

    - name: Deploy on prod
      if: ${{github.ref == 'refs/heads/main'}}
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER }}
        key: ${{ env.PRIVATE_KEY  }}
        script: git:from-image acc-squad-m1s1-front-prod ghcr.io/disilab-frba-utn-edu-ar/t2-s1-socios-front:${{ steps.date.outputs.date }}-main && ps:rebuild acc-squad-m1s1-front-prod


    - name: Deploy on dev
      if: ${{github.ref == 'refs/heads/dev'}}
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USER }}
        key: ${{ env.PRIVATE_KEY  }}
        script: git:from-image acc-squad-m1s1-front-dev ghcr.io/disilab-frba-utn-edu-ar/t2-s1-socios-front:${{ steps.date.outputs.date }}-dev && ps:rebuild acc-squad-m1s1-front-dev
